### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SandroMachado**
Fix ` misplaced.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by nlutsenko** [comment]
Hey @SandroMachado, that actually is a correct placement.
The Swift type name for a single permission is either `ReadPermission`/`WritePermission` or just `Permission`, so here we are referencing an array of `Permission` types, being `Permission`s :grin:

Does it make sense? Or you think it's just too confusing?

**Comment by nlutsenko** [comment]
Maybe just removing the `s` in the end would make it clearer?

**Comment by SandroMachado** [comment]
Yup, removing the `s` makes more sense to me :)

**Comment by nlutsenko** [comment]
Great, please update the PR, sign the CLA and I'll gladly merge this in!
Congrats on being the first outside contributor!

**Comment by SandroMachado** [comment]
@nlutsenko Thanks. I think I already signed the CLA. Can you please confirm?

**Comment by nlutsenko** [comment]
Yup, ^ that tag above means that it's signed.
Update the PR with removal of `s` and we are all good to go.

**Comment by SandroMachado** [comment]
Updated. 👍

**Pull request merged**
