### PR TITLE
Allow apiVersion to be specified with or without a \'v\' prefix

### PR DESCRIPTION
**Pull request by dhiren2**

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by nlutsenko** [comment]
Hey @dhiren2, thanks for the contribution!
Though, I am not sure why we would want to have it this way.
It used to be like that and we changed it specifically, since it's too confusing to have `v` as a prefix.
If you still think it's relevant - we probably should add support for this into the `GraphAPIVersion`, more specifically to the string literal constructors of it.

Also, broken tests look very relevant to the code change.

**Comment by dhiren2** [comment]
Hi @nlutsenko, I just started using the SDK recently, and I was confused by
the way it works at first; I had to do some digging before I found out that
the 'v' prefix is required. When thinking of versions, I think most
developers generally think of 2.1, 5.6.2, etc. and it seems like the SDK
should help abstract away the mechanics of forming the underlying URL, so
that's why I submitted the diff. That said, after reflecting on this some
more, I agree that it should be one or the other, and not both, so perhaps
this can be handled simply by highlighting it in the docs. I'd prefer not
to have the 'v', but I I'm fine with it as long as the format is clearly
highlighted in the code comments and the docs. Thanks for the feedback in
any case!

**Comment by nlutsenko** [comment]
Sounds good. Let's stick to the non `v` prefixed version, since we have support for FloatLiteralConvertible and StringLiteralConvertible (you can use either `2.7` or `"2.7"`.

**Pull request closed without merging**
