### PR TITLE
Swift 4

### PR DESCRIPTION
**Pull request by irace**
I can understand not wanting to merge this into `master` until Xcode 9 is out of beta – you may want to make a `swift-4` branch that can become the base branch for this PR?

### CODE REVIEW

**Comment by ronflima** [comment]
@irace It is important to change .travis.yaml to use a different version of Swift. The current one on your pull request is leading Travis to fail since it is using a wrong version of Xcode to compile the whole thing.

**Comment by irace** [comment]
@ronflima Good call. Just pushed an update...

**Comment by irace** [comment]
@ronflima I’m trying pretty hard to update this PR but I can’t get this repository to build for the life of me. I don’t know how folks are expected to contribute to it in its current state.

**Comment by ronflima** [comment]
@irace I have forked your repo. I'll check it out and send a PR to you. It is failing due to some warnings.

**Comment by ronflima** [comment]
It is a little hard than I thought. There are several issues avoiding this project to compile:

1. Bolts is outdated. facebook-ios-sdk is using an outdated version of Bolts. In fact, Bolts has already the fix, but it is not yet released.
1. FacebookShare target has a severe compilation problem: it is trying to assign to 3 read-only properties of `FBSDKShareLinkContent` class. So, it cannot compile at all. 
1. `LinkShareContent` has bad naming for some properties. `description` is a name to be avoided on custom classes since it may clash to `description` on NSObject and, furthermore, on Core Data names. This class is completely screwed for Swift 4. It needs a major redesign.

About travis failures: it is failing because of `pod lib lint`. It is finding a redundant constraint conformance for `GraphRequestProtocol`. I still have no idea why. Still researching.

**Comment by ethansinjin** [comment]
Hey there, I'd love to help get this merged. I'm going to take a look at the forked repository and see if I can fix at least one of the above 3 problems

**Comment by gfosco** [comment]
Thanks for the contribution.. Sorry for the delays, this will be covered in #184.

**Pull request closed without merging**
